export default {
  RUBROS:  [
    { value: 203, label: "Comida" },
    { value: 204, label: "Deportes" },
    { value: 205, label: "Entretenimiento" },
    { value: 206, label: "Educación" },
    { value: 207, label: "General" },
    { value: 208, label: "Salidas" },
    { value: 209, label: "Servicios e Impuestos" },
    { value: 210, label: "Viáticos" },
    { value: 211, label: "Varios" }
  ],
  CATEGORIAS: [
    { value: 212, label: "AFIP" },
    { value: 213, label: "Agua" },
    { value: 214, label: "Barrio Privado" },
    { value: 215, label: "Clubes y Asociaciones" },
    { value: 216, label: "Compras" },
    { value: 217, label: "Consorcio" },
    { value: 218, label: "Cooperativa" },
    { value: 219, label: "Donaciones" },
    { value: 220, label: "Electricidad" },
    { value: 221, label: "Emergencias Medicas" },
    { value: 222, label: "Establecimientos Educativo" },
    { value: 223, label: "Gas" },
    { value: 224, label: "Impuesto Municipal" },
    { value: 225, label: "Impuesto Provincial" },
    { value: 226, label: "Medicina Prepaga" },
    { value: 227, label: "Operadores de Tv" },
    { value: 228, label: "Patente" },
    { value: 229, label: "Planes de Ahorro" },
    { value: 230, label: "Préstamo" },
    { value: 231, label: "Proveedores de Internet" },
    { value: 232, label: "Recargas" },
    { value: 233, label: "Seguridad" },
    { value: 234, label: "Seguros" },
    { value: 235, label: "Seguros de retiro" },
    { value: 236, label: "Seguros de vida" },
    { value: 237, label: "Servicios Web" },
    { value: 238, label: "Tarjetas de crédito" },
    { value: 239, label: "Telefonía" },
    { value: 240, label: "Viajes y turismo" },
    { value: 241, label: "Registro Nacional" },
    { value: 242, label: "Otro" }
  ],
  ENTIDADES:  [
    { value: 543, label: "EFECTIVO" },
    { value: 243, label: "BANCO BBVA" },
    { value: 244, label: "BANCO BICA " },
    { value: 245, label: "BANCO COINAG " },
    { value: 246, label: "BANCO COLUMBIA " },
    { value: 247, label: "BANCO COMAFI SOCIEDAD ANONIMA" },
    { value: 248, label: "BANCO DE COMERCIO " },
    { value: 249, label: "BANCO DE CORRIENTES " },
    { value: 250, label: "BANCO DE GALICIA" },
    { value: 251, label: "BANCO DE LA CIUDAD DE BUENOS AIRES" },
    { value: 252, label: "BANCO DE LA NACION ARGENTINA" },
    { value: 253, label: "BANCO DE LA PAMPA " },
    { value: 254, label: "BANCO DE LA PROVINCIA DE BUENOS AIRES" },
    { value: 255, label: "BANCO DE LA PROVINCIA DE CORDOBA " },
    { value: 256, label: "BANCO DE LA REPUBLICA ORIENTAL DEL URUGU" },
    { value: 257, label: "BANCO DE SAN JUAN " },
    { value: 258, label: "BANCO DE SANTA CRUZ " },
    { value: 259, label: "BANCO DE SANTIAGO DEL ESTERO " },
    { value: 260, label: "BANCO DE SERVICIOS FINANCIEROS " },
    { value: 261, label: "BANCO DE SERVICIOS Y TRANSACCIONES " },
    { value: 262, label: "BANCO DEL SOL " },
    { value: 263, label: "BANCO HIPOTECARIO " },
    { value: 264, label: "BANCO INTERFINANZAS " },
    { value: 265, label: "BANCO ITAU ARGENTINA " },
    { value: 266, label: "BANCO JULIO SOCIEDAD ANONIMA" },
    { value: 267, label: "BANCO MACRO " },
    { value: 268, label: "BANCO MARIVA " },
    { value: 269, label: "BANCO MASVENTAS " },
    { value: 270, label: "BANCO MERIDIAN " },
    { value: 271, label: "BANCO PATAGONIA " },
    { value: 272, label: "BANCO PIANO " },
    { value: 273, label: "BANCO PROVINCIA DE TIERRA DEL FUEGO" },
    { value: 274, label: "BANCO PROVINCIA DEL NEUQUÉN" },
    { value: 275, label: "BANCO RIOJA SOCIEDAD ANONIMA UNIPERSONAL" },
    { value: 276, label: "BANCO ROELA " },
    { value: 277, label: "BANCO SAENZ " },
    { value: 278, label: "BANCO SANTANDER RIO " },
    { value: 279, label: "BANCO SUCREDITO REGIONAL U." },
    { value: 280, label: "BANCO SUPERVIELLE " },
    { value: 281, label: "BANCO VOII " },
    { value: 282, label: "BANK OF AMERICA" },
    { value: 283, label: "BNP PARIBAS" },
    { value: 284, label: "CITIBANK" },
    { value: 285, label: "COMPAÑIA FINANCIERA ARGENTINA " },
    { value: 286, label: "CORDIAL COMPAÑÍA FINANCIERA " },
    { value: 287, label: "CREDITO REGIONAL COMPAÑIA FINANCIERA S.A" },
    { value: 288, label: "FCA COMPAÑIA FINANCIERA " },
    { value: 289, label: "HSBC BANK ARGENTINA " },
    { value: 290, label: "INDUSTRIAL AND COMMERCIAL BANK OF CHINA" },
    { value: 291, label: "JPMORGAN CHASE BANK" },
    { value: 292, label: "WILOBANK " },
    { value: 293, label: "Otro" }
  ],
  TIPOSINGRESO: [
    { value: 981, label: "Sueldo" },
    { value: 982, label: "Ventas" },
    { value: 983, label: "Otros conceptos" },
    { value: 984, label: "Aguinaldo" },
    { value: 985, label: "Facturaciones particulares" },
    { value: 986, label: "Rentas" },
    { value: 987, label: "Otros" },
  ],
  MONEDAS: [
    { value: 5671, label: "ARS" },
    { value: 5672, label: "USD" },
    { value: 5673, label: "EUR" },
  ]
};
